version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rollup
    versions:
    - 2.38.0
    - 2.38.2
    - 2.38.5
    - 2.40.0
    - 2.41.2
    - 2.42.2
    - 2.43.1
    - 2.45.1
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.12.17
    - 7.13.10
    - 7.13.13
    - 7.13.15
    - 7.13.8
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.13
    - 7.12.17
    - 7.13.10
    - 7.13.12
    - 7.13.8
    - 7.13.9
  - dependency-name: "@babel/register"
    versions:
    - 7.12.13
    - 7.13.8
  - dependency-name: ava
    versions:
    - 3.15.0
